### ISSUE TITLE
I installed this plugin, but then my girlfriend guessed my password

### ISSUE THREAD

**Issue by SimplGy** [qing3962/password-protection#1]
Without my consent, she now knows that I secretly love the sound of bluegrass music while lovemaking, especially when combined with the smell of dusty woodshop.

Could you please talk to her and tell her that's not polite and I would have liked to have told her that in my own time?

(kidding, love the idea for this plugin and your README is funny. Thanks for publishing 😄)

**Comment by qing3962** [comment]
@SimplGy  Aha, you are first audience, thank you very much for your compliment! 😄

**Comment by qing3962** [comment]
Good kidding.
