### ISSUE TITLE
无法在Obsidian中启用插件

### ISSUE THREAD

**Issue by geoli91** [qing3962/password-protection#18]
你好，我从插件市场安装插件后无法启用插件，提示如下图：
![image](https://github.com/qing3962/password-protection/assets/69904123/d8f3046b-7c6b-4e71-b12a-702a32525a48)

我的Obsidian版本为v1.5.8，password protection版本为v1.1.25，系统版本为 Windows 11。

以下是我安装和启用的第三方插件，帮助排出插件冲突的问题。
![image](https://github.com/qing3962/password-protection/assets/69904123/9f20adf3-003b-4993-ba43-588f40fa60aa)
![image](https://github.com/qing3962/password-protection/assets/69904123/2cbdd3ef-5dd9-4e1f-86c9-d8604ac0c508)

感谢你开发这个插件，插件的功能也非常吸引我，非常期待能够使用该插件。

祝好

**Comment by qing3962** [comment]
我晚点看下你说的问题。

**Comment by qing3962** [comment]
我按你说的环境做了一些测试：Obsidian版本为v1.5.8，password protection版本为v1.1.25，系统版本为 Windows 11。

安装你上面列出的插件，没有发现你说的问题。

我不知道还有哪里和你的环境不一样。

**Comment by geoli91** [comment]
感谢你做的工作，应该是我这边什么环境有问题。我在我电脑上还是启用不了插件，但是在笔记本上成功了。后面我试着备份一下现在的仓库，重新安装Obsidian试试。

> 我按你说的环境做了一些测试：Obsidian版本为v1.5.8，password protection版本为v1.1.25，系统版本为 Windows 11。
> 
> 安装你上面列出的插件，没有发现你说的问题。
> 
> 我不知道还有哪里和你的环境不一样。
