### ISSUE TITLE
mouse-over + ctrl still shows the password protected note

### ISSUE THREAD

**Issue by MikkelHauge** [qing3962/password-protection#4]
double clicking a note to open it up, it asks for a password, as it should

but you can still just mouseover the note, press ctrl and read it in a little preview box.

![image](https://github.com/qing3962/password-protection/assets/92360783/5a9bf14e-863b-4d22-953c-f596a7b77dd3)

so there's basically almost no security if the sneaky person has any idea about the preview function

**Comment by qing3962** [comment]
I found you can close the review function if you would close the “page preview” plugin for security purpose. 
![Uploading EF366D23-74C7-4CE5-A7F7-CA343E5FE8E8.png…]()

**Comment by qing3962** [comment]
![f8176c5d8a05df58c7db13f105560c5](https://github.com/qing3962/password-protection/assets/14269187/93ba0bb5-1ab6-48b0-80b2-2ef88dccc723)
